
GET http://localhost:8082/api/v1/dts/status HTTP/1.1

###

GET http://localhost:8082/api/v1/dts/poker/gettablelist HTTP/1.1


###

POST http://localhost:8082/api/v1/dts/poker/addtable?name=sprint01&secret=ThatsMyPassword1 HTTP/1.1
###
POST http://localhost:8082/api/v1/dts/poker/addtable?name=sprint02&secret=ThatsMyPassword2 HTTP/1.1
###
POST http://localhost:8082/api/v1/dts/poker/addtable?name=sprint03&secret=ThatsMyPassword3 HTTP/1.1
###
POST http://localhost:8082/api/v1/dts/poker/addtable?name=sprint04&secret=ThatsMyPassword4 HTTP/1.1


###
GET http://localhost:8082/api/v1/dts/poker/gettable?name=sprint01&secret=ThatsMyPassword1 HTTP/1.1

###
GET http://localhost:8082/api/v1/dts/poker/gettable?id=0b750e8d-517c-44f0-9381-d08398945457&secret=ThatsMyPassword4 HTTP/1.1

###
PUT http://localhost:8082/api/v1/dts/poker/jointable?name=sprint01&secret=ThatsMyPassword1&participant=user4 HTTP/1.1
